# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day1' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit'

  # Pods for day1

  target 'day1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
