# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day6' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OAuthSwift', '~> 0.5.0'
  pod 'SnapKit'
  pod 'FontAwesome.swift'
  pod 'SwiftyUserDefaults'
  # Pods for day6

  target 'day6Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day6UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
