# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day4' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for day4
  pod 'SnapKit'
  pod 'FontAwesome.swift'

  target 'day4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
