# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  # Pods for day3

  target 'day3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
