# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day10' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  # Pods for day10

  target 'day10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day10UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
