# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day7' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'Alamofire'

  # Pods for day7

  target 'day7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day7UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
