# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day8' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'FontAwesome.swift'

  # Pods for day8

  target 'day8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
